# Generated by Django 2.0.4 on 2018-04-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProjectModel',
            fields=[
                ('dateCreated', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Name of Scanning Project')),
                ('description', models.CharField(max_length=1024, verbose_name='Description of scanning project')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='Date of create project')),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('createBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scanTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.ScanTaskModel')),
            ],
        ),
    ]
