# Generated by Django 2.0.4 on 2018-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanprojectmodel',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of create project'),
        ),
    ]
