# Generated by Django 2.0.4 on 2018-09-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180823_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanprojectmodel',
            old_name='createDate',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='scanprojectmodel',
            old_name='updateDate',
            new_name='dateUpdate',
        ),
    ]
