# Generated by Django 2.1.2 on 2018-10-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180926_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanprojectmodel',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name of Scanning Project'),
        ),
    ]
