# Generated by Django 2.0.4 on 2018-04-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('dateCreated', models.DateTimeField(auto_created=True)),
                ('ipAdr', models.GenericIPAddressField(primary_key=True, serialize=False, unique=True)),
                ('hostName', models.CharField(max_length=128, unique=True)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('osNAme', models.CharField(blank=True, max_length=128)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('createBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
