# Generated by Django 2.0.4 on 2018-07-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAdr', models.GenericIPAddressField(unique=True)),
                ('hostName', models.CharField(max_length=128, unique=True)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('osName', models.CharField(blank=True, max_length=128)),
                ('osVersion', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Description of Host')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
