# Generated by Django 2.1.2 on 2018-11-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20180725_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='services',
            field=models.ManyToManyField(related_name='ServiceHost', to='services.ServiceModel'),
        ),
    ]
