# Generated by Django 2.0.4 on 2018-04-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicemodel',
            unique_together={('name', 'port')},
        ),
    ]
