# Generated by Django 2.0.4 on 2018-09-26 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20180725_1510'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='fileReport',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File report'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='format',
            field=models.CharField(default=1, max_length=64, verbose_name='File format of report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosts.HostModel'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='mode',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Mode of report: 0 -Project, 1 -ScanTask, 2 -Host'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='createBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name of Report'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='scanProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ScanProjectModel'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='scanTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scans.ScanTaskModel'),
        ),
    ]
