# Generated by Django 2.0.4 on 2018-09-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180926_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Processing'), (2, 'Processed'), (3, 'Error')], default=0, verbose_name='Description of Vulnerability'),
        ),
    ]
