# Generated by Django 2.0.4 on 2018-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='mode',
            field=models.SmallIntegerField(choices=[(0, 'Project'), (1, 'ScanTask'), (2, 'Host')], default=2, verbose_name='Mode of report'),
        ),
    ]
