# Generated by Django 2.0.4 on 2018-09-27 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180927_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='createBy',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
