# Generated by Django 2.0.4 on 2018-09-27 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180927_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='createBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
