# Generated by Django 2.0.4 on 2018-10-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20180927_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='format',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'PDF'), (1, 'XML'), (2, 'XLS'), (3, 'HTML')], default=0, null=True, verbose_name='File format of report'),
        ),
    ]
