# Generated by Django 2.0.4 on 2018-10-04 07:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20181002_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='fileReport',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\tuank\\PycharmProjects\\VulnerablititesManagement\\files_data\\generated_report'), upload_to='', verbose_name='File report'),
        ),
    ]
