# Generated by Django 2.1.2 on 2018-10-22 06:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20181016_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='fileReport',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\tuank\\PycharmProjects\\VulnerablititesManagement\\files_data\\generated_report'), upload_to='', verbose_name='File report'),
        ),
    ]
