# Generated by Django 2.0.4 on 2018-07-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0003_auto_20180716_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileSubmitted', models.FileField(blank=True, null=True, upload_to='submits/%Y/%m/%d/', verbose_name='File attachment')),
                ('description', models.CharField(max_length=1024, verbose_name='Description of Vulnerability')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('scanTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.ScanTaskModel')),
            ],
        ),
    ]
