# Generated by Django 2.0.4 on 2018-07-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileSubmitted', models.FileField(upload_to='submits/%Y/%m/%d/', verbose_name='File attachment')),
                ('description', models.CharField(max_length=1024, verbose_name='Description of Vulnerability')),
                ('status', models.CharField(default='Processing', max_length=1024, verbose_name='Description of Vulnerability')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scanTask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.ScanTaskModel')),
            ],
        ),
    ]
