# Generated by Django 2.0.4 on 2018-07-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='fileSubmitted',
            field=models.FileField(upload_to='submits/%Y/%m/%d/', verbose_name='File attachment'),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='scanTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.ScanTaskModel'),
        ),
    ]
