# Generated by Django 2.0.7 on 2018-09-05 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180823_0854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submit', '0002_auto_20180725_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='submitmodel',
            name='scanTask',
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.ScanProjectModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
