# Generated by Django 2.0.7 on 2018-09-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_auto_20180903_1447'),
        ('submit', '0003_auto_20180905_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='scanTask',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='scans.ScanTaskModel'),
            preserve_default=False,
        ),
    ]
