# Generated by Django 2.0.4 on 2018-09-27 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20180906_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='fileSubmitted',
            field=models.FileField(upload_to='submits/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='File attachment'),
        ),
        migrations.AlterField(
            model_name='submitmodel',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Uploaded'), (1, 'Processing'), (2, 'Processed'), (3, 'Duplicated'), (4, 'Error')], default=0, null=True, verbose_name='Status of Submitted File'),
        ),
    ]
