# Generated by Django 2.0.4 on 2018-10-04 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_auto_20180927_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='fileSubmitted',
            field=models.FileField(storage='C:\\Users\\tuank\\PycharmProjects\\VulnerablititesManagement\\files_data\\imported_file', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='File attachment'),
        ),
    ]
