# Generated by Django 2.0.4 on 2018-07-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostScanned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.HostModel')),
                ('vulnFound', models.ManyToManyField(blank=True, to='vulnerabilities.VulnerabilityModel')),
            ],
        ),
        migrations.CreateModel(
            name='ScanTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name of Scanning Task')),
                ('isProcessed', models.BooleanField(default=True, verbose_name='If this task is processed')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description of scanning task')),
                ('startTime', models.DateTimeField(verbose_name='Start time of Scanning Task')),
                ('endTime', models.DateTimeField(verbose_name='Finish time of Scanning Task')),
                ('fileAttachment', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='File attachment')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('scanBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanBy', to=settings.AUTH_USER_MODEL)),
                ('scanInfo', models.ManyToManyField(blank=True, to='scans.ScanInfoModel')),
                ('scanProject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ScanProjectModel')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
