# Generated by Django 2.0.4 on 2018-07-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name of Scanning Task')),
                ('isProcessed', models.BooleanField(default=False, verbose_name='If this task is processed')),
                ('description', models.CharField(max_length=1024, verbose_name='Description of scanning task')),
                ('startTime', models.DateTimeField(verbose_name='Start time of Scanning Task')),
                ('endTime', models.DateTimeField(verbose_name='Finish time of Scanning Task')),
                ('fileAttachment', models.FileField(blank=True, upload_to='', verbose_name='File attachment')),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('scanBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanBy', to=settings.AUTH_USER_MODEL)),
                ('scanProject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ScanProjectModel')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
