# Generated by Django 2.0.4 on 2018-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantaskmodel',
            name='endTime',
            field=models.DateTimeField(blank=True, verbose_name='Finish time of Scanning Task'),
        ),
        migrations.AlterField(
            model_name='scantaskmodel',
            name='startTime',
            field=models.DateTimeField(blank=True, verbose_name='Start time of Scanning Task'),
        ),
    ]
