# Generated by Django 2.0.4 on 2018-07-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantaskmodel',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
