# Generated by Django 2.0.4 on 2018-07-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_auto_20180713_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantaskmodel',
            name='fileAttachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='File attachment'),
        ),
    ]
