# Generated by Django 2.0.4 on 2018-08-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_auto_20180803_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantaskmodel',
            name='scanProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ScanProjectModel'),
        ),
    ]
