# Generated by Django 2.0.7 on 2018-09-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_auto_20180823_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaninfomodel',
            name='hostScanned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScanInfoHost', to='hosts.HostModel'),
        ),
        migrations.AlterField(
            model_name='scaninfomodel',
            name='vulnFound',
            field=models.ManyToManyField(blank=True, related_name='ScanInfoVuln', to='vulnerabilities.VulnerabilityModel'),
        ),
    ]
