# Generated by Django 2.0.7 on 2018-09-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_auto_20180903_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantaskmodel',
            name='scanInfo',
            field=models.ManyToManyField(blank=True, related_name='ScanTaskScanInfo', to='scans.ScanInfoModel'),
        ),
    ]
