# Generated by Django 2.1.2 on 2018-10-27 04:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_auto_20181022_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantaskmodel',
            name='fileAttachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/fedora/PythonProject/VulnerablititesManagement/files_data/scan_attachment'), upload_to='', verbose_name='File attachment'),
        ),
    ]
