# Generated by Django 2.1.2 on 2018-11-01 07:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_auto_20181027_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantaskmodel',
            name='fileAttachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\tuank\\PycharmProjects\\VulnerablititesManagement\\files_data\\scan_attachment'), upload_to='', verbose_name='File attachment'),
        ),
    ]
