# Generated by Django 2.0.4 on 2018-04-22 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelRisk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Level of Risk')),
                ('summary', models.CharField(max_length=512, verbose_name='Summary of Vulnerability')),
                ('description', models.CharField(max_length=1024, verbose_name='Description of Vulnerability')),
            ],
        ),
    ]
