# Generated by Django 2.0.4 on 2018-06-01 02:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('scans', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelRisk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Level of Risk')),
                ('summary', models.CharField(max_length=512, verbose_name='Summary of Vulnerability')),
                ('description', models.CharField(max_length=1024, verbose_name='Description of Vulnerability')),
                ('hostScanned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosts.HostModel')),
                ('scanTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.ScanTaskModel')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceModel')),
            ],
        ),
    ]
