# Generated by Django 2.0.4 on 2018-06-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='hostScanned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.HostModel'),
        ),
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceModel'),
        ),
    ]
