# Generated by Django 2.0.4 on 2018-08-01 06:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='levelRisk',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Level of Risk'),
        ),
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceModel'),
        ),
    ]
