# Generated by Django 2.0.4 on 2018-06-01 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_auto_20180601_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='levelRisk',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Level of Risk'),
        ),
    ]
