# Generated by Django 2.0.4 on 2018-08-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_auto_20180801_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceModel'),
        ),
    ]
