# Generated by Django 2.0.4 on 2018-08-03 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_auto_20180801_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='levelRisk',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Level of Risk'),
        ),
    ]
