# Generated by Django 2.1.2 on 2018-11-01 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0004_auto_20180803_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitymodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceVulnerability', to='services.ServiceModel'),
        ),
    ]
